language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower web-component-tester
- bower install
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
env:
  global:
  - secure: eeAjCdW0MhfbV9tW+/qcuObyJ0YG8F3oEwNGHzUOXXFqLenyBaDrOm4Vjcc6h7lCeOcuAo5+9W0JuJFb753ZwKE2YtMras7zUlqxtFpwG6dL4fy6NgDEZVEwMc+VQdZOgXrqGsdYxbAHy7oEbEFOTxuyzXjgcnVUSVynx8cS2y/FytEA/h+wLTVmqkSTIDexFAwO9jMjepwrE3kjtCkDnoVWy45M5FZs1NpW+YYd70x8OoOPykimaKbUBTz1Z+X4TiQHFTj+LEqQhae4Eydb0KX/EAsjNgPRk+4xDyNuyp54/0bWx8Dz6gLHk1BMf3K9o0naFaOA4Nq1DUbSlw9dmzqkyBHZmjl6iUDGsnUyDsE9BaswCYe5j6ShrIVInGWbrnOdrV8qGdZwKdgPkKn3WT6Vzher3fHQYrwkKFmUeit6Acm3eY2+YBt9R2/X4Mga3VtbjHgmEV8mT+N0Hu0BofpxdI+gfjeGfyBMiMm6N7M+x7UV0MtCAjhr71LjVLeWoYR5ktUwss7nnEnbP6gPCuMPjnTtm3nc9sYVdglemSmfKnjXRmFGlhcEuVwaOqhUcdwpoeeyr1FcPUtoPohC+CxbEWX/wjr6HUnCPMn+39X6g98Kp5UzMlDknTTiHJQjxncte41O81sBIhidEP/xti0e7BqX0I2mhxZ9BDBN7P4=
  - secure: vVKh5PlLtshBGKnYdBthT/jmNOSsbtIBEC0J8kYotIeWt1ypGe/NWcr/yelNX+4O+V1Rk3S+y5KXaxZQCDP6vQR/jW3xdwdZyKPlhZoZD+AtUL9il+CuEv7HspXCmlQ+qrHnyHfSU51QQ5fu6Lse9szzrwYrEez2CEt2aYwKPgbuWDnNwAZh+LLq00TPC27FE0wZpon1Qy6ko5jxnEJh7e7s2NatSfzprOjdZQnaHHfF4fWKC2nUuOr+15C8jy6frUAAsbohxW1AfiCPyL7Pt+MjTvIY4tCHKRmybM753ngjXnmI8lm10dEUFC0Yk2rKuEVBBteMU20gr3dCtEhz3oWhET+qGfLYjPaf5H0I+FmVKbuySukOY/d2lu3dz/doZ7YvDtbAS2eAZ4hHsCXcgJkHW3ZeymbwcRqoC6Fna3RvRktmljLQlvX0WiD+XY5X1nXfzpJWr5CWHxTCqRS1XICIZ/fBVZPtohr3M5qqtyOdv2nOqT3yiZEgZQAxLfVj/oSLIWyv0Uh1ZGED1nXn764qTN+tyPVCW4umPbqsIIqmUzSX3zUZ4/Gm4OKxO7rU6tiEwrfTnOV84fGmkY75ATSAHdFimwT7lE+sMCuteRsuasMTwMALAp4KHsAPeEERdkS3E2MfpPPuxN0ZyLUMxUxka5vFbQ2ZGZGh6iqYGno=
