language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: latest
  sauce_connect:
    username: "sricharanBiztek"
    access_key: "d1b09f87-c78b-4b54-8097-202bb3b18c52"
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install paper-icon-button
- bower install
- export DISPLAY=:99.0
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
env:
  global:
    secure: KF2F8my/MFQyAx7TmOfnkhYEGfq7VbWyq2m2wQ6xkWdJwyItP+I+djoRQAPhDxkJ68OFu5d/zIZkuP+ExAhudVYg2Xds4YOBtnbP+IspD4xcGL9qWa627fdiehk3jq7uZvLdwzpILNxgtc+OU+QaorE8omY8WtAPPXjltM98NzKZwMSAJKUPj4tGwrl12P62Ny8i+1tFApdRIUKNxGJY8+SRD/GC8KYTJ2FkBzOWHIggHbYYcryIwuOaBbwLNBYnF8nNxeNPp/Gct8Ef7OEM8d7oQ0TDCb63J1IabDyUTmKdibuWraP3n8IadRfBMwFGG5S79zi0cLGzlEQe5NFkAEAIJzgtHNvNSmt805264iuAgYV7SaUdsxH8BcJ/FmMRIL4Z/oL4RUlakw7iHHMCGkTM7U8NM17sRdDqxLpMW4wTRK1z4R6ury1rzcTJMbsB8iiORr7M1k26ChM2jYK9MA85kV65d2cA4gYnWP6mAqbRQo/yI/XrcrshnP8qQ3gQ0wBxTJXW32PMGcHYp7Bl3aZLGrDFVBztGZ90kpA5sKBmBardi7IR2aZIKIW3EItS1K/osT522MRAAXZG2baGFpg9bFRWBuuconvHsIaqIiK/K/d+K6pwCsCiHIzxc9QhZKPmCdlKKmJhNpP+RISsHp3YwBvjH8UkIS2SjFhxgSk=
dd:
  secure: DOYDLE1JaKV7t513LOWT1/P47Yw4YGxPvPlIytFv9qHNDBuhgTrH/nxG5qF9HNzX9UIq+SXi0pIMQYJTblF0RGuK1ELFr2IWjPfepPam3ej4a0zDL/kcuKmWEkd403270OR6kf6weJUIuqYqO2RohXdP94EabHPQv3+9GkotPMCBVP2VkCazZi2LTUNjj7Ex7bKdj6C8gcd/TuJ/YXi8bNRaoXMG4658n2IsPIDKGknGW5coxPR+XTVWVqDvMSON0O9f6bCZZgx7tFCA3zd8L9CP6XtqcR9c1kj9r2ZSZzioxG9BP/Mnq6b6w8yi6Nmj+TmtlSCNyOd4BH4GAWNVcb2BMCJDE2GHYBKjPYAd2mENGYuMxmpSK9OaPawzd4tEm9j9d90Lt0SWhTHH60HIQycXo2MagBhEtbCw9b/axy/eusvX83YlpdYbC1kxq3evCmSX9xWjj3xk1gZTCnsr88b14azrLDqZytoOwowCRJLd+/Qu9vFjJ+NhCQWg0fIvdKMSHiz1YgUFVeCyulXMvym3r2BXlneFuJUOoB3iTe82Qo/HwuUN/5hboVKI+M5P0mZjCKhjibAStoZCVwhh0pOo+Kgcfjbc3cWF0RPB7G/i6AzAE0A2f4qVrlooIFe4HSk+ye1q9u+MwrNhzne6iEOno8izY5s9Kcl9qBVwk9w=
